# SIZES
TILESIZE = 50
GAMESIZE = GAMEX, GAMEY = TILESIZE * 12, TILESIZE * 12
SCREENSIZE = SCREENX, SCREENY = 1280, 720

# PLAYER
PLAYERSIZE = int(TILESIZE * 3 / 4)
PLAYERSPEED = 4

# Enemies
BASIENEMYSIZE = TILESIZE